title: razzds.net
description: razzds open-source documentation knowledge-base
#theme: null
readme_index:
  with_frontmatter: true
plugins: [jekyll-mentions]
#site_author: razzd83
#url: "https://razzds.net"
#repo_url: false
#edit_on_github: false
##logo: "logo.png"
#favicon: ""
#sticky_navigation: false
#collapse_navigation: false
#navigation_depth: 4
#includehidden: true
#titles_only: true
#nav_external_links:
#  - section: External-links
#  - title: Google Cloud Console
#    url: "https://console.cloud.google.com"
#  - title: Google Cloud Documentation
#    url: "https://docs.cloud.google.com"
#  - title: Google AI for Developers
#    url: "https://ai.google.dev"
#  - title: Google AI for Developers Documentation
#    url: "https://ai.google.dev/gemini-api/docs"
#prev_next_buttons_location: none
#search_enabled: false
#hljs_style: github
#hljs_languages:
#  - python
